server:
  port: 10010
spring:
  application:
    name: cloud-admin
  security:
    user:
      name: root
      password: root
  # ????
  mail:
    host: smtp.qq.com
    username: 771691148
    password: nfpjgoujwsdabcif
    properties:
      mail:
        smpt:
          auth: true
          starttls:
            enable: true
            required: true
#????
spring.boot.admin.notify.mail.to: hardy.wang@net263.com
# ????
spring.boot.admin.notify.mail.from: 771691148@qq.com