eureka:
  client:
    service-url:
      defaultZone: http://euk1.com:7901/eureka/
server:
  port: 90
spring:
  application:
    name: constumer

#负载均衡策略
#provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: 'com.netflix.loadbalancer.RandomRule'

#开启所有端点
management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: '*'